#!/bin/sh
npx --no -- commitlint --edit $1

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Regex pour valider le format Angular
pattern="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .+"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
    echo "Erreur: Le message de commit ne respecte pas le format"
    echo "Format attendu: <type>(scope?): description"
    echo "Exemple: feat(auth): ajout de la stratégie JWT"
    exit 1
fi

echo "✅ Format de commit valide"
