#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)

if [[ ! "$branch" =~ ^(feature|bugfix|hotfix|chore|refactor|test|doc)/[0-9]+-[a-z0-9-]+$ ]] && [[ "$branch" != "main" ]] && [[ "$branch" != "preprod" ]]; then
  echo "❌ Nom de branche invalide: $branch"
  echo "Format attendu: <type>/<ticket-id>-<description>"
  exit 1
fi
